server:
  port: 10001
  
head-count-quote-config:
  price-by-range:
    1: 2000
    101: 1500
    501: 1000
    
weather-condition-quote-config:
  condition-list:
  - cold
  - rainy
  quote-price: 5000

month-condition-quote-config:
  months-list:
  - 1
  - 11
  - 12
  quote-price: 3000
  
event-type-quote-config:
  event-type-list:
  - MUSICAL
  quote-price: -1000